//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClubManagement
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClubInformation
    {
        public int Id { get; set; }
        public string ClubName { get; set; }
        public int YearOfCreation { get; set; }
        public string City { get; set; }
    }
}
